name: Build Kombucha
on:
  workflow_dispatch:
    inputs:
      patchset:
        type: choice
        options:
          - stable
          - proton-unstable
          - unstable
      debug:
        type: boolean
        default: false
      commit:
        type: string
        default: 2df1ee28039cf84776eb1421ed90bd154cebb65f
permissions:
  contents: write
  pull-requests: read
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install Build Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y \
            autoconf \
            binutils \
            bison \
            build-essential \
            ccache \
            flex \
            gettext \
            git \
            libasound2-dev \
            libavcodec-dev \
            libavformat-dev \
            libcapi20-dev \
            libcups2-dev \
            libfontconfig-dev \
            libfreetype-dev \
            libgl-dev \
            libgnutls28-dev \
            libgphoto2-dev \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            libkrb5-dev \
            libpcap-dev \
            libpcsclite-dev \
            libpulse-dev \
            libudev-dev \
            libunwind-dev \
            libusb-1.0-0-dev \
            libsane-dev \
            libsdl2-dev \
            libv4l-dev \
            libvulkan-dev \
            libwayland-dev \
            libx11-dev \
            libxcomposite-dev \
            libxcursor-dev \
            libxext-dev \
            libxfixes-dev \
            libxi-dev \
            libxkbcommon-dev \
            libxkbregistry-dev \
            libxrandr-dev \
            libxrender-dev \
            mingw-w64 \
            ocl-icd-opencl-dev \
            samba-dev \
            wget

      - name: Install NTSync Header
        run: |
          sudo wget -O /usr/include/linux/ntsync.h \
            https://raw.githubusercontent.com/torvalds/linux/refs/tags/v6.14/include/uapi/linux/ntsync.h

      - name: Fetch Sources
        run: |
          [ ${{ inputs.patchset }} = proton-unstable ] && PART="hub.com/ValveSoftware" || PART="lab.winehq.org/wine"
          git clone https://git${PART}/wine.git --depth 1 \
            --revision=${{ inputs.commit }}

      - name: Apply Patches
        run: |
          echo "INSTALL=$GITHUB_WORKSPACE/kombucha" >> $GITHUB_ENV

          git -C wine apply "$GITHUB_WORKSPACE"/patches/${{ inputs.patchset }}/*.patch

      - name: Configure Wine
        working-directory: wine
        run: |
          export x86_64_CC="ccache x86_64-w64-mingw32-gcc"
          export x86_64_CCX="ccache x86_64-w64-mingw32-g++"
          export CC="ccache gcc"
          export CXX="ccache g++"
          export x86_64_CFLAGS="-msse4.1 -pipe ${{ inputs.debug && '-g3 -O0' || '-O3' }}"
          export x86_64_CXXFLAGS="${x86_64_CFLAGS}"
          export CFLAGS="${x86_64_CFLAGS} -fcf-protection -fno-plt -fstack-clash-protection -fstack-protector-strong"
          export CXXFLAGS="${CFLAGS}"
          export x86_64_LDFLAGS="-Wl,-O1,--sort-common,--as-needed"
          export LDFLAGS="${x86_64_LDFLAGS} -Wl,-z,relro,-z,now"
          mkdir -p ${{ env.INSTALL }}
          [ ${{ inputs.patchset }} = proton-unstable ] && ./autogen.sh
          ./configure \
            --disable-tests \
            --disable-win16 \
            --enable-archs=x86_64 \
            --prefix=${{ env.INSTALL }} \
            --with-mingw \
            --without-ffmpeg \
            --without-gstreamer \
            --without-oss \
            --without-opencl

      - name: Configure Ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Build Wine
        working-directory: wine
        run: make -j$(($(nproc) + 1))

      - name: Install Wine
        working-directory: wine
        run: make install-lib

      - name: Publish
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          TAG="${{ inputs.patchset }}${{inputs.debug && '-debug' || '' }}"
          [ ${{ inputs.patchset }} = stable ] && TAG="${TAG}+$(date --utc +%Y%m%d%H%M%S)"
          NAME="kombucha-${TAG}"

          mv "${{ env.INSTALL }}" "${NAME}"
          rm -rf "${NAME}"/share/{applications,man}
          XZ_OPT=-9 tar -Jcf "${NAME}.tar.xz" "${NAME}"

          [ ${{ inputs.patchset }} != stable ] && gh release delete --cleanup-tag "${TAG}"
          gh release create --notes "Built from Wine commit ${{ inputs.commit }}." --prerelease --title "${TAG}" "${TAG}" "${NAME}.tar.xz"
